#!/usr/bin/env python3
# gen_moe_aot.py — 从 TileLang MoE grouped-GEMM 原型（moe_grouped_proto.py 的 bf16 臂）
# 冻结出 ferrite verify MoE 两个形状的 AOT CUDA 源码，供
# `kernels/cuda/tilelang_gen/moe_bf16_shim.cu` 合入 ferrite 的 nvcc 构建。
#
# 用法（远端 B300，tilelang 0.1.14）：
#   /opt/dlami/nvme/dsv41_venv/bin/python gen_moe_aot.py <outdir>
# 产出（<outdir>）：
#   moe_up_tl.cu      # up（gate‖up）grouped GEMM，N=640 K=5120
#   moe_dn_tl.cu      # down grouped GEMM，N=5120 K=320
#   moe_tl_config.txt # 编译期常量（grid/block/smem）+ 两个内核的签名（shim 的出处）
#
# ⚠️ GENERATED — do not edit. 重生成见 kernels/cuda/tilelang_gen/PROVENANCE.md §7。
#
# =============================================================================
# 与原型（moe_grouped_proto.py::k_bf16）的两处生成差异
# =============================================================================
# 1. **裸指针 ABI**：`pass_configs={TL_DISABLE_TMA_LOWER:1,
#    TL_DISABLE_WARP_SPECIALIZED:1}`（与 gen_wkv_aot.py 同一路线，见
#    docs/agent/tilelang-integration-design.md §1.3 实验 B）。原型的默认 lowering 把
#    A/W 变成 `CUtensorMap` + TMA + warp specialization，那要求 host 侧用 driver API
#    的 `cuTensorMapEncodeTiled` 造描述符（build.sh 不链 -lcuda），且每层每方向每次
#    launch 都要重编码。裸指针 ABI 让 shim 直接把 ferrite 的 device 指针传进来。
# 2. **NSEG 烘成上界 SEG_CAP=VERIFY_ROWS*topk=36**（不再由 host 传）：TileLang 的
#    grid 维度必须是编译期常量，而真实 nseg 随路由逐位变化（本文形状 35）。多余的
#    segment 由 host 的 Eid/counts 表填 pad（Eid=0, count=0），其 C 输出不被 scatter，
#    代价是 grid.y 从 35 抬到 36（≈3% 空转）。A 的行由 host 的 gather 保证 pad 段为 0，
#    所以没有越界读。
#
# 形状/几何（来自原型 §3 的实测最优点）：
#   up : N=640 (gate‖up), K=dim=5120, E=n_routed=384, BN=256, BK=64, th=256, stg=3
#   dn : N=dim=5120,      K=inter=320,  E=384,          BN=512, BK=64, th=256, stg=2
#   A  : [NSEG*BM, K] bf16（host 已 gather + BM=16 pad；内核不做 gather/mask/atomic）
#   W  : [E, N, K]  bf16   （K 连续；up 的 N 前半 = gate(w1)，后半 = up(w3)）
#   Eid: [NSEG] int32      （每段一个 expert id，查 W 的第三坐标）
#   C  : [NSEG*BM, N] f32  （段内顺序 = expert-grouped；host 再 scatter 回 (row, slot)）

import hashlib
import sys

import tilelang
import tilelang.language as T

# 裸指针 ABI 的两个 pass_configs（设计文档 §1.3 实验 B，与 gen_wkv_aot.py 一致）。
PASS_CONFIGS = {
    tilelang.PassConfigKey.TL_DISABLE_TMA_LOWER: True,
    tilelang.PassConfigKey.TL_DISABLE_WARP_SPECIALIZED: True,
}

# ---- 冻结几何（照 docs/agent/tilelang-moe-grouped.md §2/§3）-------------------
E = 384          # n_routed（本 rank 的专家数）
DIM = 5120       # 模型维度
INTER = 320      # inter_local
BM = 16          # MMA 的最小 M：每段 pad 到 16 行
VERIFY_ROWS = 6  # m 的上界（chain_dev.rs 的 VERIFY_ROWS）
TOPK_MAX = 6     # topk（n_activated_experts）
SEG_CAP = VERIFY_ROWS * TOPK_MAX  # 36 = 最坏情况的段数上界（每 assignment 一段）

N_UP = 2 * INTER  # 640 = gate ‖ up


@tilelang.jit(pass_configs=PASS_CONFIGS)
def moe_bf16(NSEG, BM_, N, K, E_, BN, BK, threads=256, stages=3):
    """grouped GEMM：grid (ceildiv(N,BN), NSEG)，每块认领一个 (expert 段, N-tile)。"""

    @T.prim_func
    def main(
        A: T.Tensor((NSEG * BM_, K), "bfloat16"),
        W: T.Tensor((E_, N, K), "bfloat16"),
        Eid: T.Tensor((NSEG,), "int32"),
        C: T.Tensor((NSEG * BM_, N), "float32"),
    ):
        with T.Kernel(T.ceildiv(N, BN), NSEG, threads=threads) as (bx, by):
            A_sh = T.alloc_shared((BM_, BK), "bfloat16")
            B_sh = T.alloc_shared((BN, BK), "bfloat16")
            C_l = T.alloc_fragment((BM_, BN), "float32")
            e = Eid[by]
            T.clear(C_l)
            for k in T.Pipelined(T.ceildiv(K, BK), num_stages=stages):
                T.copy(A[by * BM_, k * BK], A_sh)
                T.copy(W[e, bx * BN, k * BK], B_sh)
                T.gemm(A_sh, B_sh, C_l, transpose_B=True)
            T.copy(C_l, C[by * BM_, bx * BN])

    return main


def _dump(kern, path):
    src = kern.get_kernel_source()
    with open(path, "w") as f:
        f.write(src)
    return src


def _sha(src):
    return hashlib.sha256(src.encode()).hexdigest()


def _banner(name, raw_sha, raw_bytes):
    return (
        f"// {name} — GENERATED by kernels/tilelang/gen_moe_aot.py; DO NOT EDIT.\n"
        f"// raw sha256 (this dump, before this banner) = {raw_sha}\n"
        f"// raw bytes = {raw_bytes}\n"
        f"// Regenerate: see kernels/cuda/tilelang_gen/PROVENANCE.md §7.\n"
    )


# 两个形状：up（gate‖up）与 down。BN/BK/stages 取原型 §3 的实测最优点。
UP = dict(N=N_UP, K=DIM, BN=256, BK=64, THREADS=256, STAGES=3)
DN = dict(N=DIM, K=INTER, BN=512, BK=64, THREADS=256, STAGES=2)


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else "."
    ku = moe_bf16(SEG_CAP, BM, UP["N"], UP["K"], E, UP["BN"], UP["BK"], UP["THREADS"], UP["STAGES"])
    kd = moe_bf16(SEG_CAP, BM, DN["N"], DN["K"], E, DN["BN"], DN["BK"], DN["THREADS"], DN["STAGES"])
    su = _dump(ku, f"{outdir}/moe_up_tl.cu")
    sd = _dump(kd, f"{outdir}/moe_dn_tl.cu")
    su_sha, sd_sha = _sha(su), _sha(sd)
    with open(f"{outdir}/moe_up_tl.banner", "w") as f:
        f.write(_banner("moe_up_tl.cu", su_sha, len(su)))
    with open(f"{outdir}/moe_dn_tl.banner", "w") as f:
        f.write(_banner("moe_dn_tl.cu", sd_sha, len(sd)))

    smem_up = UP["STAGES"] * (BM * UP["BK"] + UP["BN"] * UP["BK"]) * 2
    smem_dn = DN["STAGES"] * (BM * DN["BK"] + DN["BN"] * DN["BK"]) * 2
    lines = [
        "# MoE TileLang AOT config (GENERATED by gen_moe_aot.py)",
        f"E={E} DIM={DIM} INTER={INTER} BM={BM} SEG_CAP={SEG_CAP} VERIFY_ROWS={VERIFY_ROWS} TOPK_MAX={TOPK_MAX}",
        f"up: N={UP['N']} K={UP['K']} BN={UP['BN']} BK={UP['BK']} threads={UP['THREADS']} stages={UP['STAGES']}",
        f"up_grid=({(UP['N'] + UP['BN'] - 1)//UP['BN']}, {SEG_CAP})",
        f"up_smem_bytes={smem_up}",
        f"dn: N={DN['N']} K={DN['K']} BN={DN['BN']} BK={DN['BK']} threads={DN['THREADS']} stages={DN['STAGES']}",
        f"dn_grid=({(DN['N'] + DN['BN'] - 1)//DN['BN']}, {SEG_CAP})",
        f"dn_smem_bytes={smem_dn}",
        f"raw_sha256(up)={su_sha}",
        f"raw_sha256(dn)={sd_sha}",
        "",
        "--- moe_up_tl.cu signature ---",
        *[l for l in su.splitlines() if "main_kernel" in l and "__global__" in l and "launch_bounds" in l],
        "--- moe_dn_tl.cu signature ---",
        *[l for l in sd.splitlines() if "main_kernel" in l and "__global__" in l and "launch_bounds" in l],
        "",
        f"up_cu_bytes={len(su)}",
        f"dn_cu_bytes={len(sd)}",
    ]
    with open(f"{outdir}/moe_tl_config.txt", "w") as f:
        f.write("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
