#!/usr/bin/env python3
# gen_wkv_aot.py — 从 TileLang 原型（proj_fp8_tilelang.py 的 route A）冻结出 wkv 形状的
# AOT CUDA 源码，供 `kernels/cuda/tilelang_gen/` 合入 ferrite 的 nvcc 构建。
#
# 用法（远端 B300，tilelang 0.1.14）：
#   /opt/dlami/nvme/dsv41_venv/bin/python gen_wkv_aot.py <outdir>
# 产出（<outdir>）：
#   wkv_partial_tl.cu    # K-split 分片内核（裸指针 ABI，运行期 m 谓词）
#   wkv_reduce_tl.cu     # 确定性归约内核（裸指针 ABI，运行期 m 谓词）
#   wkv_tl_config.txt    # 编译期常量（grid/block/smem/ks/bN/threads）+ 签名（shim 的出处）
#
# ⚠️ GENERATED — do not edit. 重生成见 kernels/cuda/tilelang_gen/PROVENANCE.md。
#
# 口径与原型一致（route A：fp8 mma + per-32 ue8m0 scale，K-split，epilogue 直读全局 scale）：
#   a        [MPAD=16, k]       fp8 e4m3   （运行期 m 谓词：行 >= m 的 A_sh 写 0，不读 a 的那一行）
#   a_scale  [MPAD, k/32]       f32        （激活 scale，per-32-K）
#   w        [n, k]             fp8 e4m3
#   w_scale  [n/32, k/32]       ue8m0      （权重 scale，32x32 块）
#   P        [ks, MPAD, n]      f32        （分片 partial，shim 持有的常驻 scratch）
#   C        [MPAD, n]          f32        （归约输出，行 stride = n）
#
# 与原型的两处差异，都是为了让 shim 能直接把 ferrite 的 [m, k] 激活喂进来，而不用在 host
# 侧 pad 到 16 行 / 回拷 m 行：
#   1. `m` 是运行期标量；A 的 32-wide staging 带 `if i < m` 谓词（行 >= m 写 0）。
#      ⇒ 只读激活的前 m 行，不再需要 16 行 staging 缓冲，也**不会越界读**。
#      TileLang 为此在写 A_sh 前后各插一个 `__syncthreads()`（A_sh 退化为单缓冲，安全）。
#   2. reduce 的输出存储带同样的 `if row < m` 谓词 ⇒ 可**直接写 ferrite 的 `out`**，
#      前提是 `out` 的行 stride 恰为 n（shim 的形状门据此要求 `out_stride == n`）。
#      ⇒ 不需要 [16, n] 的输出 staging，也不需要 m 行的回拷。
#
# ABI 裸指针化：`pass_configs={TL_DISABLE_TMA_LOWER:1, TL_DISABLE_WARP_SPECIALIZED:1}`
# 把默认的 TMA-descriptor ABI 降为裸指针 ABI（docs/agent/tilelang-integration-design.md §1.3 实验 B）。

import sys

import tilelang
import tilelang.language as T

FP8 = "float8_e4m3fn"
E8M0 = "float8_e8m0fnu"
MPAD = 16  # mma m16n8k32 要求 M 能被 16 整除

# 已冻死的形状/几何（wkv，第一阶段唯一形状）
N, K = 512, 5120
BN = 128
KS = 8
THREADS = 128
NS = 3
RED_BN = 256

# 裸指针 ABI 的两个 pass_configs（设计文档 §1.3 实验 B）。
PASS_CONFIGS = {
    tilelang.PassConfigKey.TL_DISABLE_TMA_LOWER: True,
    tilelang.PassConfigKey.TL_DISABLE_WARP_SPECIALIZED: True,
}


@tilelang.jit(pass_configs=PASS_CONFIGS)
def proj_fp8_partial(N, K, bN, ks, threads=128, ns=3):
    """K-split 分片：grid (N/bN, ks)，每块算一段 K 的 partial，写入 P[kp]。"""
    Kc = K // ks

    @T.prim_func
    def main(A: T.Tensor((MPAD, K), FP8),
             ASC: T.Tensor((MPAD, K // 32), "float32"),
             W: T.Tensor((N, K), FP8),
             WSC: T.Tensor((N // 32, K // 32), E8M0),
             P: T.Tensor((ks, MPAD, N), "float32"),
             m: T.int32):
        with T.Kernel(T.ceildiv(N, bN), ks, threads=threads) as (bx, kp):
            A_sh = T.alloc_shared((MPAD, 32), FP8)
            W_sh = T.alloc_shared((bN, 32), FP8)
            C_l = T.alloc_fragment((MPAD, bN), "float32")
            C_p = T.alloc_fragment((MPAD, bN), "float32")
            T.clear(C_l)
            for ko in T.Pipelined(Kc // 32, num_stages=ns):
                gko = kp * (Kc // 32) + ko
                # 运行期 m 谓词：行 >= m 的 A_sh 写 0（不读激活那一行）——见文件头 (1)。
                for i, j in T.Parallel(MPAD, 32):
                    if i < m:
                        A_sh[i, j] = A[i, gko * 32 + j]
                    else:
                        A_sh[i, j] = T.cast(0, FP8)
                T.copy(W[bx * bN, gko * 32], W_sh)
                # raw fp8 mma -> 按 32-K 块的 scale 累加；scale 直读全局（不进 smem）。
                T.gemm(A_sh, W_sh, C_p, transpose_B=True, clear_accum=True)
                for i, j in T.Parallel(MPAD, bN):
                    C_l[i, j] += C_p[i, j] * ASC[i, gko] * T.cast(
                        WSC[bx * (bN // 32) + j // 32, gko], "float32")
            T.copy(C_l, P[kp, 0, bx * bN])

    return main


@tilelang.jit(pass_configs=PASS_CONFIGS)
def proj_fp8_reduce(ks, N, bN=256):
    """确定性归约：按 kp 升序求和 ks 个 partial，只写前 m 行（行 stride = N）。"""
    IDX = tuple(range(ks))

    @T.prim_func
    def main(P: T.Tensor((ks, MPAD, N), "float32"),
             C: T.Tensor((MPAD, N), "float32"),
             m: T.int32):
        with T.Kernel(T.ceildiv(N, bN), threads=256) as bx:
            for i, j in T.Parallel(MPAD, bN):
                if i < m:
                    C[i, bx * bN + j] = sum([P[kq, i, bx * bN + j] for kq in IDX])

    return main


def _dump(kern, path):
    src = kern.get_kernel_source()
    with open(path, "w") as f:
        f.write(src)
    return src


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else "."
    kp = proj_fp8_partial(N, K, BN, KS, THREADS, NS)
    kr = proj_fp8_reduce(KS, N, RED_BN)
    sp = _dump(kp, f"{outdir}/wkv_partial_tl.cu")
    sr = _dump(kr, f"{outdir}/wkv_reduce_tl.cu")

    lines = [
        "# wkv TileLang AOT config (GENERATED by gen_wkv_aot.py)",
        f"N={N} K={K} BN={BN} KS={KS} THREADS={THREADS} NS={NS} MPAD={MPAD} RED_BN={RED_BN}",
        f"partial_grid=({(N + BN - 1)//BN}, {KS})",
        f"partial_block={THREADS}",
        f"partial_smem_bytes={NS * MPAD * 32 + NS * BN * 32}",
        f"reduce_grid=({(N + RED_BN - 1)//RED_BN},)",
        f"reduce_block={RED_BN}",
        "",
        "--- wkv_partial_tl.cu signature ---",
        *[l for l in sp.splitlines() if "main_kernel" in l and "__global__" in l and "launch_bounds" in l],
        "--- wkv_reduce_tl.cu signature ---",
        *[l for l in sr.splitlines() if "main_kernel" in l and "__global__" in l and "launch_bounds" in l],
        "",
        f"partial_cu_bytes={len(sp)}",
        f"reduce_cu_bytes={len(sr)}",
    ]
    with open(f"{outdir}/wkv_tl_config.txt", "w") as f:
        f.write("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
