//! Engram: the n-gram hash tables.
//!
//! Two backbone layers (1 and 14 in the released config) carry a giant
//! embedding table. At every position the model looks up `max_ngram_size - 1`
//! n-grams (2-gram .. 4-gram), each split over `n_heads` heads, so each token
//! fetches `(max_ngram_size - 1) * n_heads = 24` rows of `head_dim = 256`
//! fp8 weights. The hash ids are turned into a key/value pair by `wkv`, gated
//! by a normalised dot product against the residual stream, and added back
//! into every hc copy (see [`crate::ops::engram_forward`]).
//!
//! Faithful to `inference/engram.py`:
//!   * the primes are drawn deterministically (`find_next_prime`, starting at
//!     `engram_vocab_size - 1`, never reused) — recomputed here and checked
//!     against the reference values in the tests;
//!   * the per-(layer, lookback) multipliers are the reference's model
//!     constants (numpy `default_rng(10007 * layer_id)`); they are stored as a
//!     table because reproducing numpy's SeedSequence/PCG64 seeding exactly is
//!     a dependency-free claim we do not want to make in the hot path. The
//!     provenance and the verification script are recorded below;
//!   * the hash is a rolling XOR over the multiplied compressed token ids,
//!     reduced modulo the (n-gram size, head) bucket prime, plus the bucket
//!     offset.
//!
//! `hash_ids` layout is `[batch, seq, n_engram_layers, n_hash_cols]` with
//! `n_hash_cols = (max_ngram_size - 1) * n_heads`, matching the reference.

use crate::config::Dsv41Config;

/// `DEAD` marks a position that takes no part in an n-gram (an image span).
pub const DEAD: i64 = -1;

/// The reference's multiplier table (`compute_hash_multipliers`), indexed by
/// `[layer_index_in_engram_layer_ids][lookback 0..max_ngram_size]`.
///
/// Generated by:
/// ```text
/// generator = np.random.default_rng(10007 * layer_id)
/// values = generator.integers(0, (int64::MAX // compressed_vocab) // 2,
///                             size=(max_ngram_size,), dtype=np.int64)
/// multipliers = values * 2 + 1
/// ```
/// with `compressed_vocab = 99092` and `layer_id ∈ {1, 14}`. Kept odd by
/// construction; bounded so `token_id * multiplier` cannot overflow int64.
pub const MULTIPLIERS: [[i64; 4]; 2] = [
    [76632096046245, 4839876093313, 35959672319349, 73987337458391],
    [67716810739261, 51510806800915, 30921347202721, 82619226485591],
];

/// The multiplier bound the reference derives.
pub fn multiplier_bound(compressed_vocab: u64) -> i64 {
    ((i64::MAX as u64 / compressed_vocab) / 2) as i64
}

fn is_prime(n: u64) -> bool {
    if n < 2 {
        return false;
    }
    if n % 2 == 0 {
        return n == 2;
    }
    let mut d = 3u64;
    while d.saturating_mul(d) <= n {
        if n % d == 0 {
            return false;
        }
        d += 2;
    }
    true
}

/// The smallest prime above `start` not yet handed out (reference
/// `find_next_prime`).
fn find_next_prime(start: u64, seen: &mut Vec<u64>) -> u64 {
    let mut c = start + 1;
    loop {
        if is_prime(c) && !seen.contains(&c) {
            seen.push(c);
            return c;
        }
        c += 1;
    }
}

/// Bucket layout of one engram layer's table.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct EngramLayerLayout {
    /// `[n_ngram][n_heads]` bucket moduli, in draw order.
    pub primes: Vec<Vec<u64>>,
    /// `[n_ngram * n_heads]` bucket starts inside the layer's table.
    pub offsets: Vec<u64>,
    /// Table rows (unsharded).
    pub num_embeddings: u64,
}

impl EngramLayerLayout {
    pub fn n_hash_cols(&self) -> usize {
        self.offsets.len()
    }

    /// The bucket a hash column belongs to (primes/offsets are flat in the
    /// same order: `[n_ngram][n_heads]`).
    pub fn column(&self, col: usize) -> (u64, u64) {
        let n_heads = self.primes.first().map(|p| p.len()).unwrap_or(0);
        let ng = col / n_heads.max(1);
        let h = col % n_heads.max(1);
        (self.primes[ng][h], self.offsets[col])
    }
}

/// The full engram layout: one entry per `engram_layer_ids`.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct EngramLayout {
    pub layers: Vec<EngramLayerLayout>,
    pub max_ngram_size: usize,
    pub n_heads: usize,
    pub head_dim: usize,
    /// `engram_layer_ids[i] -> i`
    pub layer_ids: Vec<usize>,
}

impl EngramLayout {
    pub fn from_config(cfg: &Dsv41Config) -> Option<Self> {
        if cfg.engram_layer_ids.is_empty() || cfg.engram_max_ngram_size <= 1 {
            return None;
        }
        let n_ngram = cfg.engram_max_ngram_size - 1;
        let mut seen: Vec<u64> = Vec::new();
        let mut layers = Vec::new();
        for (i, _lid) in cfg.engram_layer_ids.iter().enumerate() {
            let mut primes = Vec::with_capacity(n_ngram);
            let mut current = cfg.engram_vocab_size - 1;
            for _ in 0..n_ngram {
                let mut sizes = Vec::with_capacity(cfg.engram_n_heads);
                for _ in 0..cfg.engram_n_heads {
                    current = find_next_prime(current, &mut seen);
                    sizes.push(current);
                }
                primes.push(sizes);
            }
            let flat: Vec<u64> = primes.iter().flatten().copied().collect();
            let mut offsets = Vec::with_capacity(flat.len());
            let mut acc = 0u64;
            for p in &flat {
                offsets.push(acc);
                acc += p;
            }
            layers.push(EngramLayerLayout {
                primes,
                offsets,
                num_embeddings: cfg.engram_num_embeddings.get(i).copied().unwrap_or(0),
            });
        }
        Some(EngramLayout {
            layers,
            max_ngram_size: cfg.engram_max_ngram_size,
            n_heads: cfg.engram_n_heads,
            head_dim: cfg.engram_head_dim,
            layer_ids: cfg.engram_layer_ids.clone(),
        })
    }

    pub fn n_hash_cols(&self) -> usize {
        self.layers.first().map(|l| l.n_hash_cols()).unwrap_or(0)
    }

    /// Index of `layer` inside `engram_layer_ids`, if it carries a table.
    pub fn engram_index(&self, layer: usize) -> Option<usize> {
        self.layer_ids.iter().position(|&l| l == layer)
    }

    pub fn multipliers(&self, engram_index: usize) -> &[i64; 4] {
        &MULTIPLIERS[engram_index]
    }
}

/// The compressed token map: original token id -> compressed id. Tokens whose
/// decoded text normalises alike collapse together, so `" The"`, `"the"` and
/// `"THE"` hash identically.
///
/// The map is a build artifact (it needs the tokenizer's normalizer chain), so
/// the engine loads it from the converted checkpoint. `identity()` is the
/// in-crate fallback used by tests and by tiny synthetic configs.
#[derive(Debug, Clone, Default)]
pub struct TokenMap {
    pub map: Vec<i64>,
    /// The compressed vocab size — every hash multiplier derives from it.
    pub compressed_vocab: u64,
}

impl TokenMap {
    pub fn identity(vocab: usize) -> Self {
        TokenMap {
            map: (0..vocab as i64).collect(),
            compressed_vocab: vocab as u64,
        }
    }

    pub fn from_table(map: Vec<i64>, compressed_vocab: u64) -> Self {
        TokenMap { map, compressed_vocab }
    }

    #[inline]
    pub fn get(&self, token: i64) -> i64 {
        let i = token as usize;
        if i < self.map.len() {
            self.map[i]
        } else {
            0
        }
    }
}

/// Per-sequence n-gram state: the compressed-token cache plus the hash ids.
///
/// Mutation mirrors the reference's `NgramHashState.forward`: the compressed
/// ids are written into the cache at `[start_pos, start_pos + seqlen)`, and
/// look-back stops at the sequence start and at any `DEAD` token.
#[derive(Debug)]
pub struct NgramHashState {
    /// `[max_batch, max_seq]` compressed ids (i64).
    pub cache: Vec<i64>,
    pub max_batch: usize,
    pub max_seq: usize,
    pub pad_id: i64,
}

impl NgramHashState {
    pub fn new(cfg: &Dsv41Config, map: &TokenMap) -> Self {
        NgramHashState {
            cache: vec![0; cfg.max_batch_size * cfg.max_seq_len],
            max_batch: cfg.max_batch_size,
            max_seq: cfg.max_seq_len,
            pad_id: map.get(cfg.engram_pad_id as i64),
        }
    }

    #[inline]
    fn cache_at(&self, b: usize, pos: i64) -> i64 {
        if pos < 0 {
            return self.pad_id;
        }
        let p = pos as usize;
        if p >= self.max_seq {
            return self.pad_id;
        }
        self.cache[b * self.max_seq + p]
    }

    /// Compute the hash ids for `[start_pos, start_pos + seqlen)` of one batch
    /// row. `token_mask`: `None` in text-only batches, otherwise `false` for
    /// positions that must not take part in an n-gram (image spans).
    ///
    /// Returns `[seqlen, n_layers, n_hash_cols]` row-major.
    pub fn forward_row(
        &mut self,
        layout: &EngramLayout,
        map: &TokenMap,
        batch_row: usize,
        input_ids: &[u32],
        start_pos: usize,
        token_mask: Option<&[bool]>,
    ) -> Vec<i64> {
        let seqlen = input_ids.len();
        // 1. refresh the compressed-token cache (image spans become DEAD)
        for (i, &id) in input_ids.iter().enumerate() {
            let mut c = map.get(id as i64);
            if let Some(m) = token_mask {
                if !m.get(i).copied().unwrap_or(true) {
                    c = DEAD;
                }
            }
            self.cache[batch_row * self.max_seq + start_pos + i] = c;
        }
        let n_ngram = layout.max_ngram_size - 1;
        let nh = layout.n_heads;
        let n_cols = n_ngram * nh;
        let mut out = vec![0i64; seqlen * layout.layers.len() * n_cols];

        // 2. per position: rolling XOR over the multiplied lookback ids
        for s in 0..seqlen {
            let pos = (start_pos + s) as i64;
            // tokens[shift] with the blocked rule from the reference
            let mut tokens = [0i64; 8];
            let mut blocked = false;
            for shift in 0..layout.max_ngram_size {
                let src = self.cache_at(batch_row, (pos - shift as i64).max(0));
                blocked = blocked || (pos < shift as i64) || (src == DEAD);
                tokens[shift] = if blocked { self.pad_id } else { src };
            }
            for (li, layer) in layout.layers.iter().enumerate() {
                let mult = layout.multipliers(li);
                let mut rolling = tokens[0].wrapping_mul(mult[0]);
                for i in 1..layout.max_ngram_size {
                    let p = tokens[i].wrapping_mul(mult[i]);
                    rolling ^= p;
                    let row = 0usize; // primes are flat [ngram][head]
                    let _ = row;
                    for h in 0..nh {
                        let (lm, off) = layer.column((i - 1) * nh + h);
                        let v = (rolling.rem_euclid(lm as i64)) + off as i64;
                        let idx = (s * layout.layers.len() + li) * n_cols + (i - 1) * nh + h;
                        out[idx] = v;
                    }
                }
            }
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Dsv41Config;

    #[test]
    fn primes_match_reference_values() {
        // Golden values from the reference (numpy/sympy) for the released config:
        //   start = engram_vocab_size - 1 = 15999999, 2 layers x 3 n-gram sizes x 8 heads
        let cfg = Dsv41Config::production();
        let l = EngramLayout::from_config(&cfg).unwrap();
        let want_l0 = [
            [16000057u64, 16000079, 16000081, 16000097, 16000121, 16000129, 16000133, 16000183],
            [16000189, 16000207, 16000211, 16000253, 16000277, 16000289, 16000307, 16000321],
            [16000339, 16000381, 16000393, 16000399, 16000403, 16000409, 16000447, 16000463],
        ];
        let want_l1 = [
            [16000477u64, 16000487, 16000499, 16000507, 16000511, 16000573, 16000609, 16000627],
            [16000667, 16000669, 16000693, 16000697, 16000711, 16000729, 16000759, 16000769],
            [16000781, 16000799, 16000813, 16000819, 16000841, 16000877, 16000879, 16000889],
        ];
        for (i, want) in [want_l0, want_l1].iter().enumerate() {
            for (ng, row) in want.iter().enumerate() {
                assert_eq!(l.layers[i].primes[ng], row.to_vec(), "layer {i} ngram {ng}");
            }
        }
        // offsets are the running sum of the flat prime list
        assert_eq!(l.layers[0].offsets[0], 0);
        assert_eq!(l.layers[0].offsets[1], 16000057);
        assert_eq!(l.layers[0].offsets[8], 128000880);
        assert_eq!(l.layers[0].offsets[23], 368005705);
        // the last bucket ends exactly at the table size
        let last = l.layers[0].offsets[23] + l.layers[0].primes[2][7];
        assert_eq!(last, 384006168);
        assert_eq!(l.n_hash_cols(), 24);
    }

    #[test]
    fn multiplier_constants_are_odd_and_in_range() {
        let cfg = Dsv41Config::production();
        let bound = multiplier_bound(cfg.engram_compressed_vocab_size);
        assert_eq!(bound, 46539438283891);
        for layer in MULTIPLIERS.iter() {
            for &m in layer.iter() {
                assert_eq!(m % 2, 1, "multipliers are kept odd");
                // values are < 2*bound after the *2+1 that keeps them odd
                assert!(m > 0 && m < 2 * bound + 1, "{m} out of range");
            }
        }
    }

    #[test]
    fn hash_ids_land_inside_their_buckets() {
        let cfg = Dsv41Config::production();
        let layout = EngramLayout::from_config(&cfg).unwrap();
        let map = TokenMap::identity(129280);
        let mut st = NgramHashState::new(&cfg, &map);
        let ids: Vec<u32> = vec![100, 200, 300, 400, 500];
        let h = st.forward_row(&layout, &map, 0, &ids, 0, None);
        let n_cols = layout.n_hash_cols();
        assert_eq!(h.len(), ids.len() * layout.layers.len() * n_cols);
        for s in 0..ids.len() {
            for (li, layer) in layout.layers.iter().enumerate() {
                for c in 0..n_cols {
                    let (m, off) = layer.column(c);
                    let v = h[(s * layout.layers.len() + li) * n_cols + c];
                    assert!(v >= off as i64 && v < (off + m) as i64, "s={s} c={c} v={v}");
                }
            }
        }
    }

    #[test]
    fn hash_matches_hand_computed_rolling_xor() {
        // At pos 0 the reference clamps every lookback to cache[0] and then
        // blocks shifts > 0 (pos < shift), so the token vector is
        // [id, pad, pad, pad]. The rolling XOR therefore has a closed form we
        // can compute here and compare against the implementation — this
        // checks the multipliers, the primes AND the reduction together.
        let cfg = Dsv41Config::production();
        let layout = EngramLayout::from_config(&cfg).unwrap();
        let map = TokenMap::identity(129280);
        let pad = map.get(cfg.engram_pad_id as i64);
        let id = 12345i64;
        let mut st = NgramHashState::new(&cfg, &map);
        let h = st.forward_row(&layout, &map, 0, &[id as u32], 0, None);
        let nh = layout.n_heads;
        let n_cols = layout.n_hash_cols();
        for (li, layer) in layout.layers.iter().enumerate() {
            let mult = layout.multipliers(li);
            let t = [id, pad, pad, pad];
            let mut rolling = t[0].wrapping_mul(mult[0]);
            for i in 1..layout.max_ngram_size {
                rolling ^= t[i].wrapping_mul(mult[i]);
                for c in (i - 1) * nh..i * nh {
                    let (lm, off) = layer.column(c);
                    let want = rolling.rem_euclid(lm as i64) + off as i64;
                    let got = h[li * n_cols + c];
                    assert_eq!(got, want, "layer {li} col {c}");
                }
            }
        }
    }

    #[test]
    fn dead_tokens_break_the_ngram() {
        let cfg = Dsv41Config::production();
        let layout = EngramLayout::from_config(&cfg).unwrap();
        let map = TokenMap::identity(129280);
        let mut a = NgramHashState::new(&cfg, &map);
        // Two rows with the same token at position 3 but different history.
        let ids = [10u32, 20, 30, 40];
        let h0 = a.forward_row(&layout, &map, 0, &ids, 0, None);
        let mask_all_dead = [false; 4];
        let mut b = NgramHashState::new(&cfg, &map);
        let h1 = b.forward_row(&layout, &map, 0, &ids, 0, Some(&mask_all_dead));
        assert_ne!(h0, h1, "an image span must change the 4-gram hash");
        // a fully dead span collapses to the all-pad hash
        let mut c = NgramHashState::new(&cfg, &map);
        let h2 = c.forward_row(&layout, &map, 1, &[7, 8, 9, 11], 0, Some(&mask_all_dead));
        assert_eq!(h1, h2);
    }

    #[test]
    fn decode_split_is_consistent_with_prefill() {
        // hashing 3 tokens then 2 more must equal hashing 5 at once
        let cfg = Dsv41Config::production();
        let layout = EngramLayout::from_config(&cfg).unwrap();
        let map = TokenMap::identity(129280);
        let mut whole = NgramHashState::new(&cfg, &map);
        let h_whole = whole.forward_row(&layout, &map, 0, &[5, 6, 7, 8, 9], 0, None);
        let mut split = NgramHashState::new(&cfg, &map);
        let h_a = split.forward_row(&layout, &map, 0, &[5, 6, 7], 0, None);
        let h_b = split.forward_row(&layout, &map, 0, &[8, 9], 3, None);
        let n_cols = layout.n_hash_cols();
        let nl = layout.layers.len();
        let tail = &h_whole[3 * nl * n_cols..];
        assert_eq!(h_b, tail.to_vec());
        assert_eq!(&h_whole[..3 * nl * n_cols], &h_a[..]);
    }
}
