// moe_up_tl.cu — GENERATED by kernels/tilelang/gen_moe_aot.py; DO NOT EDIT.
// raw sha256 (this dump, before this banner) = 7499f395cbc1e585cb8cb2838a062623b14f752079e43dcc7fbaac60cdd15d3c
// raw bytes = 10766
// up (gate‖up) grouped GEMM: N=640 K=5120 E=384 BM=16 NSEG=36 BN=256 BK=64 th=256 stg=3.
// A [NSEG*16,5120] bf16 / W [384,640,5120] bf16 / Eid [NSEG] i32 / C [NSEG*16,640] f32.
// Regenerate: see kernels/cuda/tilelang_gen/PROVENANCE.md §7.
#if defined(_MSC_VER) && !defined(__clang__) && _MSC_VER < 1940
#define _tl_orig_alignas alignas
#define alignas(N) _tl_orig_alignas((N) <= 64 ? (N) : 64)
#include <cuda.h>
#undef alignas
#define alignas _tl_orig_alignas
#endif
#include <tl_templates/cuda/instruction/mma.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/scan.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void main_kernel(const bfloat16_t* __restrict__ A, float* __restrict__ C, const int* __restrict__ Eid, const bfloat16_t* __restrict__ W);
extern "C" __global__ void __launch_bounds__(256, 1) main_kernel(const bfloat16_t* __restrict__ A, float* __restrict__ C, const int* __restrict__ Eid, const bfloat16_t* __restrict__ W) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* A_sh = ((void*)((char*)buf_dyn_shmem + 0));
  void* B_sh = ((void*)((char*)buf_dyn_shmem + 6144));
  float C_l[16];
  int e = Eid[((int)blockIdx.y)];
  #pragma unroll
  for (int i = 0; i < 4; ++i) {
    float broadcast_var = 0x0p+0f/*0.000000e+00*/;
    *(float4*)(C_l + (i * 4)) = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
  }
  tl::cp_async_gs<8>((&(((bfloat16_t*)A_sh)[((((((((int)threadIdx.x) >> 4) * 64) + (((((((int)threadIdx.x) & 127) >> 6) + ((((int)threadIdx.x) & 15) >> 3)) & 1) * 32)) + (((((((int)threadIdx.x) & 63) >> 5) + ((((int)threadIdx.x) & 7) >> 2)) & 1) * 16)) + (((((((int)threadIdx.x) & 31) >> 4) + ((((int)threadIdx.x) & 3) >> 1)) & 1) * 8)) + ((((int)threadIdx.x) & 1) * 4))])), (&(A[(((((int)blockIdx.y) * 81920) + ((((int)threadIdx.x) >> 4) * 5120)) + ((((int)threadIdx.x) & 15) * 4))])));
  #pragma unroll
  for (int i_1 = 0; i_1 < 8; ++i_1) {
    tl::cp_async_gs_conditional<16>((&(((bfloat16_t*)B_sh)[(((((i_1 * 2048) + ((((int)threadIdx.x) >> 3) * 64)) + (((((((int)threadIdx.x) & 63) >> 5) + ((((int)threadIdx.x) & 7) >> 2)) & 1) * 32)) + (((((((int)threadIdx.x) & 31) >> 4) + ((((int)threadIdx.x) & 3) >> 1)) & 1) * 16)) + (((((((int)threadIdx.x) & 15) >> 3) + (((int)threadIdx.x) & 1)) & 1) * 8))])), (&(W[(((((((int64_t)e) * (int64_t)3276800) + (((int64_t)((int)blockIdx.x)) * (int64_t)1310720)) + (((int64_t)i_1) * (int64_t)163840)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)3) * (int64_t)5120)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)7) * (int64_t)8))])), ((((((((int)blockIdx.x) * 2) + (i_1 >> 2)) < 5) && (e < 384)) && (0 <= e)) && (((((int)blockIdx.x) * 2) + (i_1 >> 2)) < 5)));
  }
  tl::cp_async_commit();
  tl::cp_async_gs<8>((&(((bfloat16_t*)A_sh)[(((((((((int)threadIdx.x) >> 4) * 64) + (((((((int)threadIdx.x) & 127) >> 6) + ((((int)threadIdx.x) & 15) >> 3)) & 1) * 32)) + (((((((int)threadIdx.x) & 63) >> 5) + ((((int)threadIdx.x) & 7) >> 2)) & 1) * 16)) + (((((((int)threadIdx.x) & 31) >> 4) + ((((int)threadIdx.x) & 3) >> 1)) & 1) * 8)) + ((((int)threadIdx.x) & 1) * 4)) + 1024)])), (&(A[((((((int)blockIdx.y) * 81920) + ((((int)threadIdx.x) >> 4) * 5120)) + ((((int)threadIdx.x) & 15) * 4)) + 64)])));
  #pragma unroll
  for (int i_2 = 0; i_2 < 8; ++i_2) {
    tl::cp_async_gs_conditional<16>((&(((bfloat16_t*)B_sh)[((((((i_2 * 2048) + ((((int)threadIdx.x) >> 3) * 64)) + (((((((int)threadIdx.x) & 63) >> 5) + ((((int)threadIdx.x) & 7) >> 2)) & 1) * 32)) + (((((((int)threadIdx.x) & 31) >> 4) + ((((int)threadIdx.x) & 3) >> 1)) & 1) * 16)) + (((((((int)threadIdx.x) & 15) >> 3) + (((int)threadIdx.x) & 1)) & 1) * 8)) + 16384)])), (&(W[((((((((int64_t)e) * (int64_t)3276800) + (((int64_t)((int)blockIdx.x)) * (int64_t)1310720)) + (((int64_t)i_2) * (int64_t)163840)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)3) * (int64_t)5120)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)7) * (int64_t)8)) + (int64_t)64)])), ((((((((int)blockIdx.x) * 2) + (i_2 >> 2)) < 5) && (e < 384)) && (0 <= e)) && (((((int)blockIdx.x) * 2) + (i_2 >> 2)) < 5)));
  }
  tl::cp_async_commit();
  for (int k = 0; k < 78; ++k) {
    __syncthreads();
    tl::cp_async_gs<8>((&(((bfloat16_t*)A_sh)[((((((((k + 2) % 3) * 1024) + ((((int)threadIdx.x) >> 4) * 64)) + (((((((int)threadIdx.x) & 127) >> 6) + ((((int)threadIdx.x) & 15) >> 3)) & 1) * 32)) + (((((((int)threadIdx.x) & 63) >> 5) + ((((int)threadIdx.x) & 7) >> 2)) & 1) * 16)) + (((((((int)threadIdx.x) & 31) >> 4) + ((((int)threadIdx.x) & 3) >> 1)) & 1) * 8)) + ((((int)threadIdx.x) & 1) * 4))])), (&(A[(((((((int)blockIdx.y) * 81920) + ((((int)threadIdx.x) >> 4) * 5120)) + (k * 64)) + ((((int)threadIdx.x) & 15) * 4)) + 128)])));
    #pragma unroll
    for (int i_3 = 0; i_3 < 8; ++i_3) {
      tl::cp_async_gs_conditional<16>((&(((bfloat16_t*)B_sh)[((((((((k + 2) % 3) * 16384) + (i_3 * 2048)) + ((((int)threadIdx.x) >> 3) * 64)) + (((((((int)threadIdx.x) & 63) >> 5) + ((((int)threadIdx.x) & 7) >> 2)) & 1) * 32)) + (((((((int)threadIdx.x) & 31) >> 4) + ((((int)threadIdx.x) & 3) >> 1)) & 1) * 16)) + (((((((int)threadIdx.x) & 15) >> 3) + (((int)threadIdx.x) & 1)) & 1) * 8))])), (&(W[(((((((((int64_t)e) * (int64_t)3276800) + (((int64_t)((int)blockIdx.x)) * (int64_t)1310720)) + (((int64_t)i_3) * (int64_t)163840)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)3) * (int64_t)5120)) + (((int64_t)k) * (int64_t)64)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)7) * (int64_t)8)) + (int64_t)128)])), ((((((((int)blockIdx.x) * 2) + (i_3 >> 2)) < 5) && (e < 384)) && (0 <= e)) && (((((int)blockIdx.x) * 2) + (i_3 >> 2)) < 5)));
    }
    tl::cp_async_commit();
    tl::cp_async_wait<2>();
    __syncthreads();
    {
      bfloat16_t A_local[8];
      bfloat16_t B_local[16];
      for (int ki = 0; ki < 4; ++ki) {
        tl::ptx_ldmatrix_x4((&(((bfloat16_t*)A_sh)[((((((k % 3) * 1024) + ((((int)threadIdx.x) & 15) * 64)) + (((((((int)threadIdx.x) & 7) >> 2) + (ki >> 1)) & 1) * 32)) + (((((((int)threadIdx.x) & 3) >> 1) + (ki & 1)) & 1) * 16)) + (((((((int)threadIdx.x) & 31) >> 4) + (((int)threadIdx.x) & 1)) & 1) * 8))])), (&(A_local[0])));
        #pragma unroll
        for (int i_4 = 0; i_4 < 2; ++i_4) {
          tl::ptx_ldmatrix_x4((&(((bfloat16_t*)B_sh)[(((((((((k % 3) * 16384) + ((((int)threadIdx.x) >> 5) * 2048)) + (i_4 * 1024)) + (((((int)threadIdx.x) & 31) >> 4) * 512)) + ((((int)threadIdx.x) & 7) * 64)) + (((((((int)threadIdx.x) & 7) >> 2) + (ki >> 1)) & 1) * 32)) + (((((((int)threadIdx.x) & 3) >> 1) + (ki & 1)) & 1) * 16)) + (((((((int)threadIdx.x) & 15) >> 3) + (((int)threadIdx.x) & 1)) & 1) * 8))])), (&(B_local[(i_4 * 8)])));
        }
        for (int j = 0; j < 2; ++j) {
          tl::mma_sync<tl::DataType::kBFloat16, tl::DataType::kBFloat16, tl::DataType::kFloat32, 16, 8, 16, false, true>(reinterpret_cast<float*>(C_l + (j * 8)), reinterpret_cast<const unsigned*>(A_local + 0), reinterpret_cast<const unsigned*>(B_local + (j * 8)));
          tl::mma_sync<tl::DataType::kBFloat16, tl::DataType::kBFloat16, tl::DataType::kFloat32, 16, 8, 16, false, true>(reinterpret_cast<float*>(C_l + ((j * 8) + 4)), reinterpret_cast<const unsigned*>(A_local + 0), reinterpret_cast<const unsigned*>(B_local + ((j * 8) + 4)));
        }
      }
    }
  }
  tl::cp_async_wait<1>();
  __syncthreads();
  {
    bfloat16_t A_local_1[8];
    bfloat16_t B_local_1[16];
    for (int ki_1 = 0; ki_1 < 4; ++ki_1) {
      tl::ptx_ldmatrix_x4((&(((bfloat16_t*)A_sh)[(((((((int)threadIdx.x) & 15) * 64) + (((((((int)threadIdx.x) & 7) >> 2) + (ki_1 >> 1)) & 1) * 32)) + (((((((int)threadIdx.x) & 3) >> 1) + (ki_1 & 1)) & 1) * 16)) + (((((((int)threadIdx.x) & 31) >> 4) + (((int)threadIdx.x) & 1)) & 1) * 8))])), (&(A_local_1[0])));
      #pragma unroll
      for (int i_5 = 0; i_5 < 2; ++i_5) {
        tl::ptx_ldmatrix_x4((&(((bfloat16_t*)B_sh)[((((((((((int)threadIdx.x) >> 5) * 2048) + (i_5 * 1024)) + (((((int)threadIdx.x) & 31) >> 4) * 512)) + ((((int)threadIdx.x) & 7) * 64)) + (((((((int)threadIdx.x) & 7) >> 2) + (ki_1 >> 1)) & 1) * 32)) + (((((((int)threadIdx.x) & 3) >> 1) + (ki_1 & 1)) & 1) * 16)) + (((((((int)threadIdx.x) & 15) >> 3) + (((int)threadIdx.x) & 1)) & 1) * 8))])), (&(B_local_1[(i_5 * 8)])));
      }
      for (int j_1 = 0; j_1 < 2; ++j_1) {
        tl::mma_sync<tl::DataType::kBFloat16, tl::DataType::kBFloat16, tl::DataType::kFloat32, 16, 8, 16, false, true>(reinterpret_cast<float*>(C_l + (j_1 * 8)), reinterpret_cast<const unsigned*>(A_local_1 + 0), reinterpret_cast<const unsigned*>(B_local_1 + (j_1 * 8)));
        tl::mma_sync<tl::DataType::kBFloat16, tl::DataType::kBFloat16, tl::DataType::kFloat32, 16, 8, 16, false, true>(reinterpret_cast<float*>(C_l + ((j_1 * 8) + 4)), reinterpret_cast<const unsigned*>(A_local_1 + 0), reinterpret_cast<const unsigned*>(B_local_1 + ((j_1 * 8) + 4)));
      }
    }
  }
  tl::cp_async_wait<0>();
  __syncthreads();
  {
    bfloat16_t A_local_2[8];
    bfloat16_t B_local_2[16];
    for (int ki_2 = 0; ki_2 < 4; ++ki_2) {
      tl::ptx_ldmatrix_x4((&(((bfloat16_t*)A_sh)[((((((((int)threadIdx.x) & 15) * 64) + (((((((int)threadIdx.x) & 7) >> 2) + (ki_2 >> 1)) & 1) * 32)) + (((((((int)threadIdx.x) & 3) >> 1) + (ki_2 & 1)) & 1) * 16)) + (((((((int)threadIdx.x) & 31) >> 4) + (((int)threadIdx.x) & 1)) & 1) * 8)) + 1024)])), (&(A_local_2[0])));
      #pragma unroll
      for (int i_6 = 0; i_6 < 2; ++i_6) {
        tl::ptx_ldmatrix_x4((&(((bfloat16_t*)B_sh)[(((((((((((int)threadIdx.x) >> 5) * 2048) + (i_6 * 1024)) + (((((int)threadIdx.x) & 31) >> 4) * 512)) + ((((int)threadIdx.x) & 7) * 64)) + (((((((int)threadIdx.x) & 7) >> 2) + (ki_2 >> 1)) & 1) * 32)) + (((((((int)threadIdx.x) & 3) >> 1) + (ki_2 & 1)) & 1) * 16)) + (((((((int)threadIdx.x) & 15) >> 3) + (((int)threadIdx.x) & 1)) & 1) * 8)) + 16384)])), (&(B_local_2[(i_6 * 8)])));
      }
      for (int j_2 = 0; j_2 < 2; ++j_2) {
        tl::mma_sync<tl::DataType::kBFloat16, tl::DataType::kBFloat16, tl::DataType::kFloat32, 16, 8, 16, false, true>(reinterpret_cast<float*>(C_l + (j_2 * 8)), reinterpret_cast<const unsigned*>(A_local_2 + 0), reinterpret_cast<const unsigned*>(B_local_2 + (j_2 * 8)));
        tl::mma_sync<tl::DataType::kBFloat16, tl::DataType::kBFloat16, tl::DataType::kFloat32, 16, 8, 16, false, true>(reinterpret_cast<float*>(C_l + ((j_2 * 8) + 4)), reinterpret_cast<const unsigned*>(A_local_2 + 0), reinterpret_cast<const unsigned*>(B_local_2 + ((j_2 * 8) + 4)));
      }
    }
  }
  if (((((int)blockIdx.x) * 2) + (((int)threadIdx.x) >> 7)) < 5) {
    #pragma unroll
    for (int i_7 = 0; i_7 < 8; ++i_7) {
      *(float2*)(C + (((((((((int)blockIdx.y) * 10240) + ((i_7 & 1) * 5120)) + (((((int)threadIdx.x) & 31) >> 2) * 640)) + (((int)blockIdx.x) * 256)) + ((((int)threadIdx.x) >> 5) * 32)) + ((i_7 >> 1) * 8)) + ((((int)threadIdx.x) & 3) * 2))) = *(float2*)(C_l + (i_7 * 2));
    }
  }
}

